### ISSUE TITLE
DAG's error

### ISSUE THREAD

**Issue by ndik11** [dm-logv/airflow-tutorial#2]
I created empty tg_main connection, but I get ×Broken DAG: [/dags/dags/update_reports.py] 'bot_token' anyway.
Just clonned your project, didnt change anything. Pls help

`[2021-02-17 15:51:47,629] {dagbag.py:239} ERROR - Failed to import: /dags/dags/update_reports.py
airflow_1     | Traceback (most recent call last):
airflow_1     |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 236, in process_file
airflow_1     |     m = imp.load_source(mod_name, filepath)
airflow_1     |   File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
airflow_1     |     module = _load(spec)
airflow_1     |   File "<frozen importlib._bootstrap>", line 696, in _load
airflow_1     |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
airflow_1     |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
airflow_1     |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
airflow_1     |   File "/dags/dags/update_reports.py", line 43, in <module>
airflow_1     |     trigger_rule=TriggerRule.ONE_FAILED)
airflow_1     |   File "/dags/commons/operators.py", line 28, in __init__
airflow_1     |     self._hook = TelegramBotHook(tg_bot_conn_id)
airflow_1     |   File "/dags/commons/hooks.py", line 22, in __init__
airflow_1     |     self.get_conn()
airflow_1     |   File "/dags/commons/hooks.py", line 26, in get_conn
airflow_1     |     self.tg_bot_token = extra['bot_token']
airflow_1     | KeyError: 'bot_token'
`

**Comment by dmlogv** [comment]
To avoid this error you have to fill-up an `extra` section in your connection `tg_main`:

```json
{"bot_token": "Your:TelegramBotToken"}
```

as described in the paragraph https://habr.com/ru/post/512386/#razbiraem-kastomnyy-operator and in the TelegramBotHook description: https://github.com/dm-logv/airflow-tutorial/blob/151d1c2057c310c6d56ff5679d0ce9e9a99844d0/dags/commons/hooks.py#L10
